**One-hot encoding**

In [1]:
import pandas as pd

# 샘플 데이터 생성
data = {'Fruit': ['Apple', 'Banana', 'Cherry', 'Apple']}
df = pd.DataFrame(data)

# One-hot encoding 수행
encoded_df = pd.get_dummies(df, columns=['Fruit'])

print(encoded_df)


   Fruit_Apple  Fruit_Banana  Fruit_Cherry
0            1             0             0
1            0             1             0
2            0             0             1
3            1             0             0


In [2]:
from sklearn.preprocessing import OneHotEncoder

# 샘플 데이터 생성
data = [['Apple'], ['Banana'], ['Cherry'], ['Apple']]

# OneHotEncoder 객체 생성 및 fitting
encoder = OneHotEncoder(sparse=False)
encoded_data = encoder.fit_transform(data)

print(encoded_data)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


**Label Encoding**

In [3]:
from sklearn.preprocessing import LabelEncoder

# 샘플 데이터 생성
data = ['Apple', 'Banana', 'Cherry', 'Apple']

# LabelEncoder 객체 생성 및 fitting
encoder = LabelEncoder()
encoded_data = encoder.fit_transform(data)

print(encoded_data)  # 예: [0, 1, 2, 0]

# 필요한 경우, 원래의 범주로 역변환도 가능
original_data = encoder.inverse_transform(encoded_data)
print(original_data)  # 예: ['Apple', 'Banana', 'Cherry', 'Apple']

[0 1 2 0]
['Apple' 'Banana' 'Cherry' 'Apple']


**Min-Max Scaling**

In [4]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# 샘플 데이터 생성
data = np.array([[10.0], [20.0], [30.0], [40.0]])

# MinMaxScaler 객체 생성 및 fitting
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)

[[0.        ]
 [0.33333333]
 [0.66666667]
 [1.        ]]


**Standard Scaling (Z-score normalization)**

In [5]:
from sklearn.preprocessing import StandardScaler

# 샘플 데이터 생성
data = np.array([[10.0], [20.0], [30.0], [40.0]])

# StandardScaler 객체 생성 및 fitting
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)

[[-1.34164079]
 [-0.4472136 ]
 [ 0.4472136 ]
 [ 1.34164079]]
